//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPasswordGeneratorService")]
public interface IPasswordGeneratorService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordGeneratorService/Generate", ReplyAction="http://tempuri.org/IPasswordGeneratorService/GenerateResponse")]
    string Generate(string key, string source, bool lower, bool upper, bool digit, bool special, int length);
}
